language: node_js
node_js:
- '8'
deploy:
  provider: gae
  keyfile: gae.json
  project: node-travis-test
  verbosity:debug
  on:master
  version:tre
before_install:
- openssl aes-256-cbc -K $encrypted_5e9d9f5d657d_key -iv $encrypted_5e9d9f5d657d_iv
  -in gae.json.enc -out gae.json -d
